version: '3.8'

services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: changemetoo

  cache:
    image: redis:alpine
    restart: always

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - database
      - cache
    volumes:
      - ./data/var:/app/var
      - ./data/nginx:/etc/nginx/http.d
      - ./data/certs:/etc/letsencrypt
      - ./data/logs:/app/storage/logs
    environment:
      APP_URL: https://pterodactyl.example.com
      APP_TIMEZONE: UTC
      APP_SERVICE_AUTHOR: noreply@example.com
      TRUSTED_PROXIES: "*"
      MAIL_FROM: noreply@example.com
      MAIL_DRIVER: smtp
      MAIL_HOST: mail
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: "true"
      DB_PASSWORD: changeme
      DB_HOST: database
      DB_PORT: 3306
      APP_ENV: production
      APP_ENVIRONMENT_ONLY: false
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: cache

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
